# Data analysis tools 2
**Lecture and exercises for week 6B** in Digital Methods, University of Copenhagen

*Note: Due to the sudden demand for remote learning, we are experimenting with different ways of creating a good
remote learning experience. Therefore your feedback and suggestions are encouraged. You can give feedback
anonymously through [this web form](https://ulfaslak.com/vent) or reach out to a teacher. This notebook contains
bits of lecturing and exercises interweaved. There is no seperate lecture file, everything you need is in here.
Later this week I will upload solutions possibly in video format, explaining the solutions. It is important to note
that we will probably iterate on this format, so we ask for your patience if we mess up.*

***Also, due to this special format, it is important you DON'T SKIP AHEAD and go straight for the exercises. Try
to consume the content of this notebook in the order it is presented, otherwise you may miss important points
that we, for obvious reasons, cannot communicate in person.***

In [1]:
from IPython.display import HTML

def video_html(url):
    return f"""
    <div align="middle">
    <video width="50%" controls>
      <source src="{url}" type="video/mp4">
    </video></div>"""

## 1. `NumPy` + `pandas` = ❤️
### *(a brief primer)*

When manipulating data in Python, NumPy and pandas are your go-to tools. Numpy is an extremely fast *low-level*
library for manipulating N-dimensional *arrays* (from lists (1D), to tables (2D), to boxes (3D), etc.). It also
contains a bunch of mathematical tools for advanced analysis. pandas is a fast *high-level* library for manipulating
series (1D) and tables (2D). It let's you do a lot of very sophisticated data manipulation operations without
a whole lot of code (hence the term *high-level*). In summary:
* **NumPy** is the fundamental package for scientific computing with Python.<br>
* **pandas** is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool

Friedolin gave you a nice introduction to these libraries last week, but **for a short recap, watch the video below**.

In [2]:
HTML(video_html('https://www.dropbox.com/s/5vbwkjzd6nrk24g/1_numpy_and_pandas_min.mov?raw=1'))

And here is a quick demonstration of how to use NumPy and pandas in Python.

In [3]:
HTML(video_html('https://www.dropbox.com/s/1d0l26ilr80ez31/2_numpy_and_pandas_example_min.mov?raw=1'))

> **Ex. 1**: Import `numpy`. Use the `np.random.randint` function to create a 10 by 2 array of random integers.
Display this array.
>
> *Hint: Remember you can do`?np.random.randint` to display the documentation. Read about the `size` argument.
It says to pass it a "tuple". A tuple is like a list, only it uses parentheses, not square brackets. Try passing
it the tuple `(10, 2)`.*

In [4]:
import numpy as np

In [5]:
import pandas as pd

In [33]:
arr = np.random.randint(2, 100, size = (10, 2))

arr

array([[14, 83],
       [69, 93],
       [66, 21],
       [44, 26],
       [47, 70],
       [84, 98],
       [80, 91],
       [13, 19],
       [25, 25],
       [32, 23]])

> **Ex. 2**: Import `pandas`. Load the array you just created as a `pd.DataFrame`. Name the row and column indices
(anything you like). Display this DataFrame.

In [34]:
arr = pd.DataFrame(arr, index = ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg', 'Randers', 'Kolding', 'Horsens',
                                 'Vejle', 'Roskilde'], columns = ['Dogs', 'Cats'])

arr

Dogs  Cats
Copenhagen    14    83
Aarhus        69    93
Odense        66    21
Aalborg       44    26
Esbjerg       47    70
Randers       84    98
Kolding       80    91
Horsens       13    19
Vejle         25    25
Roskilde      32    23

> **Ex. 3**: Turn the DataFrame back into an array! Display the type of the resulting array. What does this reveal
about the connection between pandas and NumPy?
>
> *Hint: You can do this by getting it's `values` attribute. To get an attribute from an object, you use the "dot-
operator". Like `object.attribute`.*

In [36]:
type(arr.values)

numpy.ndarray

## Merging/joining datasets

It's not uncommon that we need to stick to pieces of data together to make a new table. Sometimes merging data is
straight forward, both pieces have the same shape and we can just slab one on top of the other and all is good. But
other times, one piece has more, fewer or different columns. Sometimes, data points in either dataset needs to be
merged somehow. **In the video below we have look at different cases and how to manage them**.

In [37]:
HTML(video_html('https://www.dropbox.com/s/qprehqimhkp9lpe/3_joining_data_min.mov?raw=1'))

Also watch this video where I give **some examples** of how to merge data in pandas.

In [38]:
HTML(video_html('https://www.dropbox.com/s/qj85zi8yq6jbrxp/4_joining_data_example.mov?raw=1'))

> **Ex. 4**: Consider the two pandas dataframes `df1` and `df2` below. 

In [39]:
df1 = pd.DataFrame(
    np.random.randint(0, 10, size=(3, 4)),
    index=[0, 1, 2], columns=['a', 'b', 'c', 'd']
)

df2 = pd.DataFrame(
    np.random.randint(0, 10, size=(5, 3)),
    index=[1, 2, 3, 4, 5], columns=['c', 'd', 'e']
)

In [40]:
df1

a  b  c  d
0  4  6  7  5
1  1  1  3  9
2  2  5  1  9

In [41]:
df2

c  d  e
1  1  5  0
2  6  9  4
3  3  4  0
4  3  4  2
5  8  0  5

> Join `df1` and `df2` (using `pd.concat`) with argument `axis=1`.
>
> 1. What is the resulting shape if you merge them using an outer join?
> 1. What is the resulting shape if you merge them using an inner join?

In [55]:
# outer join

pd.concat([df1, df2], join = 'outer', axis = 1)

a    b    c    d    c    d    e
0  4.0  6.0  7.0  5.0  NaN  NaN  NaN
1  1.0  1.0  3.0  9.0  1.0  5.0  0.0
2  2.0  5.0  1.0  9.0  6.0  9.0  4.0
3  NaN  NaN  NaN  NaN  3.0  4.0  0.0
4  NaN  NaN  NaN  NaN  3.0  4.0  2.0
5  NaN  NaN  NaN  NaN  8.0  0.0  5.0

In [56]:
# inner join, axis = 1

pd.concat([df1, df2], join = 'inner', axis = 1)

a  b  c  d  c  d  e
1  1  1  3  9  1  5  0
2  2  5  1  9  6  9  4

> **Ex. 5**: Again, use `pd.concat` to outer join `df1` and `df2`, but this time use `axis=0`.
> 1. Qualitatively, what is the difference now that `axis=1`, compared to when `axis=0`? You can for examlpe
display the two results side by size and try to spot the pattern difference.
> 1. Read about the `axis` argument (remember you can use `?pd.concat` to launch the docs). Does this correspond
with your understanding? Can you predict what an inner join of `df1` and `df2` with `axis=0` would look like?

In [57]:
# inner join, axis = 0

pd.concat([df1, df2], join = 'outer', axis = 0)

/Users/mathildemeiling/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  This is separate from the ipykernel package so we can avoid doing imports until


a    b  c  d    e
0  4.0  6.0  7  5  NaN
1  1.0  1.0  3  9  NaN
2  2.0  5.0  1  9  NaN
1  NaN  NaN  1  5  0.0
2  NaN  NaN  6  9  4.0
3  NaN  NaN  3  4  0.0
4  NaN  NaN  3  4  2.0
5  NaN  NaN  8  0  5.0

> **Ex. 6**: So we have learned that in pandas, anything can be concatenated. That's not the case in NumPy!
Consider the two arrays below `arr1` and `arr2`.

In [58]:
arr1 = np.random.randint(0, 10, size=(3, 4))
arr2 = np.random.randint(0, 10, size=(3, 3))

In [63]:
print(arr1)

print(arr2)

[[3 0 8 4]
 [7 6 2 7]
 [1 7 6 5]]
[[0 2 5]
 [0 2 5]
 [3 5 6]]


> 1. Use `np.vstack` to concatenate `arr1` and `arr2` below. What does the error say? And why?
> 1. Now use `np.hstack` to concatenate `arr1` and `arr2`. It works! But why?

In [64]:
np.vstack([arr1, arr2]) 
#the columns / rows must match exactly - this concatenate using columns i.e. no 100 % match

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 3

In [60]:
np.hstack([arr1, arr2]) #these is doable because of the same number of rows

array([[3, 0, 8, 4, 0, 2, 5],
       [7, 6, 2, 7, 0, 2, 5],
       [1, 7, 6, 5, 3, 5, 6]])

## Summary statistics

It is useful to be able to summarize a dataset in a few key numbers. *Summary statistics*
does that for us. pandas has a set of nice tools to make this very easy! First let's load
some data

In [67]:
# Import
from sklearn.datasets import load_wine

# Structure as pd.DataFrame
data = load_wine()
wine_df = pd.DataFrame(data['data'], columns=data['feature_names'])

# display
wine_df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

This dataset contains information and measurements on 173 Italian wines. Read the column
names and look at the values and try to make sense of it. What are typical values for each
feature? How much do they deviate? What's the lowest they get? etc. Here's a short video 
where I explain different statistics:

In [68]:
HTML(video_html('https://www.dropbox.com/s/bwlhgpwcbq3652l/5_summary_statistics.mov?raw=1'))    

> **Ex. 7**: If you followed my instructions above, you should hopefully felt that staring
at data like that isn't the most meaningful way to spend your time. So go ahead and run
`wine_df.describe()`. What does it show?
1. Explain what the *mean* and *std* values tell you about. Inside which range of alcohol
content does 68% of the data lie?
1. Explain what *min*, *max* and the *25%*, *50%*, and *75%* values mean.
1. What is another common word for the *50%* value?

In [71]:
wine_df.describe()

# 1. The mean gives me the average, and the std tells me to which extent the values deviate from the mean or in 
# other words within what range the 68 % of the data closest to the mean lie. In this case within roughly 
# 12.2 and 13.8

# 2. Min = smallest/lowest value, max = biggest/highest, 25% = the number 25 % into the sorted data set, same
# for the 50 % and 75 %. 

# 3. 50 % = the median 

alcohol  malic_acid         ash  alcalinity_of_ash   magnesium  \
count  178.000000  178.000000  178.000000         178.000000  178.000000   
mean    13.000618    2.336348    2.366517          19.494944   99.741573   
std      0.811827    1.117146    0.274344           3.339564   14.282484   
min     11.030000    0.740000    1.360000          10.600000   70.000000   
25%     12.362500    1.602500    2.210000          17.200000   88.000000   
50%     13.050000    1.865000    2.360000          19.500000   98.000000   
75%     13.677500    3.082500    2.557500          21.500000  107.000000   
max     14.830000    5.800000    3.230000          30.000000  162.000000   

       total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
count     178.000000  178.000000            178.000000       178.000000   
mean        2.295112    2.029270              0.361854         1.590899   
std         0.625851    0.998859              0.124453         0.572359   
min         0.980000    0.340000              0.130000         0.410000   
25%         1.742500    1.205000              0.270000         1.250000   
50%         2.355000    2.135000              0.340000         1.555000   
75%         2.800000    2.875000              0.437500         1.950000   
max         3.880000    5.080000              0.660000         3.580000   

       color_intensity         hue  od280/od315_of_diluted_wines      proline  
count       178.000000  178.000000                    178.000000   178.000000  
mean          5.058090    0.957449                      2.611685   746.893258  
std           2.318286    0.228572                      0.709990   314.907474  
min           1.280000    0.480000                      1.270000   278.000000  
25%           3.220000    0.782500                      1.937500   500.500000  
50%           4.690000    0.965000                      2.780000   673.500000  
75%           6.200000    1.120000                      3.170000   985.000000  
max          13.000000    1.710000                      4.000000  1680.000000

## Group-by operations

Often times we have some data, and need to know e.g. the average of every datapoint
that matched a certain criteria. Or our datapoints are categorized by some variable
(e.g. *sex* categorizes people into *male*, *female* and sometimes *non-binary*), and we want
to count how many datapoints that fall in each category. Then we use *group-by*!

We are going to use the Titanic dataset for this exercise. Each row is a passanger, and each
column describes a feature of the passangers. Please stare at it in silence for 2 minutes, and
then watch the video below.

In [77]:
titanic_df = pd.read_csv('https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv')
titanic_df

Survived  Pclass                                               Name  \
0           0       3                             Mr. Owen Harris Braund   
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2           1       3                              Miss. Laina Heikkinen   
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4           0       3                            Mr. William Henry Allen   
..        ...     ...                                                ...   
882         0       2                               Rev. Juozas Montvila   
883         1       1                        Miss. Margaret Edith Graham   
884         0       3                     Miss. Catherine Helen Johnston   
885         1       1                               Mr. Karl Howell Behr   
886         0       3                                 Mr. Patrick Dooley   

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0      male  22.0                        1                        0   7.2500  
1    female  38.0                        1                        0  71.2833  
2    female  26.0                        0                        0   7.9250  
3    female  35.0                        1                        0  53.1000  
4      male  35.0                        0                        0   8.0500  
..      ...   ...                      ...                      ...      ...  
882    male  27.0                        0                        0  13.0000  
883  female  19.0                        0                        0  30.0000  
884  female   7.0                        1                        2  23.4500  
885    male  26.0                        0                        0  30.0000  
886    male  32.0                        0                        0   7.7500  

[887 rows x 8 columns]

In [73]:
HTML(video_html('https://www.dropbox.com/s/yejuzmw7x0vw14r/6_groupby.mov?raw=1'))    

> **Ex. 8**: Use the `groupby` operation to get the *mean* feature values of survivors and non-survivors.
* How big is the age difference?
* What about the 'Pclass' (low values closer to first class)? 
* Number of siblings/spouses aboard?
* Parents/children aboard?
* Ticket price (fare)?
>
> Do you see any systematic differences between survivors and non-survivors?

In [78]:
titanic_df.groupby('Survived').mean()

Pclass        Age  Siblings/Spouses Aboard  \
Survived                                                 
0         2.528440  30.138532                 0.557798   
1         1.950292  28.408392                 0.473684   

          Parents/Children Aboard       Fare  
Survived                                      
0                        0.332110  22.208584  
1                        0.464912  48.395408

> **Ex. 9**: Try grouping on both 'Survived' and 'Sex', and then `count`ing the number of
rows in either group and subgroup. Do you see a pattern in who survives and who does not?

In [96]:
titanic_df.groupby(['Sex', 'Survived']).count()

Pclass  Name  Age  Siblings/Spouses Aboard  \
Sex    Survived                                               
female 0             81    81   81                       81   
       1            233   233  233                      233   
male   0            464   464  464                      464   
       1            109   109  109                      109   

                 Parents/Children Aboard  Fare  
Sex    Survived                                 
female 0                              81    81  
       1                             233   233  
male   0                             464   464  
       1                             109   109

Object `count` not found.
